apps/front/forms.py
# coding=utf-8
from wtforms import Form, StringField
from wtforms.validators import Email, Length, InputRequired, DataRequired


class LoginForm(Form):
    '''前台登陆验证'''
    email = StringField(validators=[Email(message='请输入正确格式的邮箱'), InputRequired('请输入邮箱')])
    password = StringField(validators=[Length(min=6, max=20, message='请输入正确格式的密码')])
    remember = StringField(validators=[])


class StudentLoginForm(LoginForm):
    pass


class TeacherLoginForm(LoginForm):
    pass


class AddChoiceFrom(Form):
    type = StringField(validators=[])
    content = StringField(validators=[InputRequired(message='请输入题干')])
    option_A = StringField(validators=[InputRequired(message='请输入A选项')])
    option_B = StringField(validators=[InputRequired(message='请输入B选项')])
    option_C = StringField(validators=[InputRequired(message='请输入C选项')])
    option_D = StringField(validators=[InputRequired(message='请输入D选项')])
    result = StringField(validators=[])
    parse = StringField(validators=[InputRequired(message='请输入该题解析')])


class AddShortAnswerForm(Form):
    content = StringField(validators=[InputRequired('请输入题干')])
    result = StringField(validators=[InputRequired('请输入答案')])
    type = StringField(validators=[])


class AddProgramForm(AddShortAnswerForm):
    pass


class PostTestPagerForm(Form):
    '''发布试卷验证表单'''
    id = StringField(validators=[])
    test_time = StringField(validators=[Length(8, 19, message='考试时间不合法'),InputRequired('请输入考试时间')])
    test_class = StringField(validators=[])


class AddTestPagerForm(Form):
    name = StringField(validators=[InputRequired('请输入试卷名称')])

apps/front/__init__.py
import apps.front.hooks

apps/front/views.py
# coding=utf-8

from flask import Blueprint, render_template, views, request, g, redirect,\
    url_for, session
from apps.front.forms import LoginForm, AddChoiceFrom, AddShortAnswerForm, \
    AddProgramForm, PostTestPagerForm, AddTestPagerForm
from config import session as db_session
from apps.front.models import Student, Teacher, Choice, ShortAnswer, Program,\
    TestPager, Class, Score, StudentChoiceResult, StudentProgramResult, \
    StudentShortAnswerResult
import config
from apps.front.decorators import student_login_required, teacher_login_required
from sqlalchemy import func


front_bp = Blueprint('front', __name__)


@front_bp.route('/')
def index():
    return redirect(url_for("front.student_login"))


@front_bp.route("/login_out/")
@student_login_required
def login_out():
    del session[config.STUDENT_EMAIL]
    return redirect(url_for("front.student_login"))


class StudentLoginView(views.MethodView):
    def __render(self, error=None):
        return render_template('front/front_student_login.html', error=error)

    def get(self):
        return self.__render()

    def post(self):
        form = LoginForm(request.form)
        if form.validate():
            email = request.form.get('email')
            password = request.form.get('password')
            remember = request.form.get('remember')
            user = db_session.query(Student).filter(Student.student_email == email).first()
            if user:
                if user.check_student_password(password):
                    session[config.STUDENT_EMAIL] = user.student_email
                    # 如果勾选了自动登陆
                    if remember:
                        session.permanent = True
                    return redirect(url_for("front.exam"))
                else:
                    return self.__render("密码不正确，请重新输入")
            else:
                return self.__render("用户不存在，请检查邮箱是否输入正确")
        else:
            errors = form.errors
            error = errors.popitem()[1][0]
            return self.__render(error)


class TeacherLoginView(views.MethodView):
    def __render(self, error=None):
        return render_template("front/front_teacher_login.html", error=error)

    def get(self):
        return self.__render()

    def post(self):
        form = LoginForm(request.form)
        if form.validate():
            email = request.form.get('email')
            password = request.form.get('password')
            remember = request.form.get('remember')
            user = db_session.query(Teacher).filter(Teacher.teacher_email == email).first()
            if user:
                if user.check_teacher_password(password):
                    session[config.TEACHER_EMAIL] = user.teacher_email
                    # 如果勾选了自动登陆
                    if remember:
                        session.permanent = True
                    return redirect(url_for('front.teacher_info'))
                else:
                    return self.__render("密码不正确，请重新输入")
            else:
                return self.__render("用户不存在，请检查邮箱是否输入正确")
        else:
            errors = form.errors
            error = errors.popitem()[1][0]
            return self.__render(error)


class ExamView(views.MethodView):
    decorators = [student_login_required]
    def get(self):
        user = db_session.query(Student).filter(Student.student_email==g.student_user.student_email).first()
        Scores = db_session.query(Score).filter(Score.score_student_id==user.student_id).all()
        return render_template('front/front_exam.html', Scores=Scores)


class StudentCenterView(views.MethodView):
    decorators = [student_login_required]
    def get(self):
        return render_template('front/front_student_center.html')


@front_bp.route('/teacher_info/')
@teacher_login_required
def teacher_info():
    return render_template("front/front_teacher_info.html")


@front_bp.route('/teacher_logout/')
@teacher_login_required
def teacher_logout():
    del session[config.TEACHER_EMAIL]
    return redirect(url_for('front.teacher_login'))


# 注册url规则
front_bp.add_url_rule('/student_login/', view_func=StudentLoginView.as_view('student_login'))
front_bp.add_url_rule('/teacher_login/', view_func=TeacherLoginView.as_view('teacher_login'))
front_bp.add_url_rule('/exam/', view_func=ExamView.as_view('exam'))
front_bp.add_url_rule('/studentCenter/', view_func=StudentCenterView.as_view('studentCenter'))


class TeacherAddChoiceView(views.MethodView):
    def __render(self, message=None):
        return render_template("front/front_add_choice.html", message=message)

    decorators = [teacher_login_required]
    def get(self):
        return self.__render()

    def post(self):
        form = AddChoiceFrom(request.form)
        if form.validate():
            type = form.type.data
            content = form.content.data
            option_A = form.option_A.data
            option_B = form.option_B.data
            option_C = form.option_C.data
            option_D = form.option_D.data
            result = form.result.data
            parse = form.parse.data
            choice = Choice(choice_type=type, choice_content=content, choice_option_A=option_A,
                            choice_option_B=option_B, choice_option_C=option_C, choice_option_D=option_D,
                            choice_result=result, choice_parse=parse)
            db_session.add(choice)
            db_session.commit()
            return self.__render('success')
        else:
            message = form.errors.popitem()[1][0]
            return self.__render(message=message)


class TeacherAddShortAnswer(views.MethodView):
    def __render(self, message=None):
        return render_template("front/front_add_short_answer.html", message=message)

    decorators = [teacher_login_required]
    def get(self):
        return self.__render()

    def post(self):
        form = AddShortAnswerForm(request.form)
        if form.validate():
            type = form.type.data
            content = form.content.data
            result = form.result.data
            short_answer = ShortAnswer(short_answer_type=type, short_answer_content=content, short_answer_result=result)
            db_session.add(short_answer)
            db_session.commit()
            return self.__render('success')
        else:
            message = form.errors.popitem()[1][0]
            return self.__render(message=message)


class TeacherAddProgram(views.MethodView):
    def __render(self, message=None):
        return render_template("front/front_add_program.html", message=message)

    decorators = [teacher_login_required]
    def get(self):
        return self.__render()

    def post(self):
        form = AddProgramForm(request.form)
        if form.validate():
            type = form.type.data
            content = form.content.data
            result = form.result.data
            program = Program(program_type=type, program_content=content, program_result=result)
            db_session.add(program)
            db_session.commit()
            return self.__render('success')
        else:
            message = form.errors.popitem()[1][0]
            return self.__render(message=message)


class AddTestPage(views.MethodView):
    decorators = [teacher_login_required]
    def get(self):
        return render_template('front/front_add_test_page.html')

    def post(self):
        form = AddTestPagerForm(request.form)
        if form.validate():
            # 接收前台数据
            choiceSize = int(request.form["choiceSize"])
            choiceScore = int(request.form["choiceScore"])
            shortAnswerSize = int(request.form["shortAnswerSize"])
            shortAnswerScore = int(request.form["shortAnswerScore"])
            programSize = int(request.form["programSize"])
            programScore = int(request.form["programScore"])
            type = request.form["type"]
            name = request.form['name'].strip()
            # 试卷的总分等于 =
            # 选择器的个数*单个选择题的分值 + 简答题的个数*单个简答题的分值 + 程序设计题的个数*单个程序设计提的分值
            totalscore = (choiceSize*choiceScore) + (shortAnswerSize*shortAnswerScore) + (programSize*programScore)
            count_choice = db_session.query(Choice).filter(Choice.choice_type==type).count()
            count_short_answer = db_session.query(ShortAnswer).filter(ShortAnswer.short_answer_type==type).count()
            count_program = db_session.query(Program).filter(Program.program_type==type).count()
            # 如果数据库选择题的个数小于需要生成的个数
            if count_choice < choiceSize:
                # 把所有的题全部抽出来
                choices = db_session.query(Choice).all()
                message1 = '题库中选择题不够%s个, 现已全部引用' % choiceSize
            # 如果需要生成的选择题的个数小于数据库中存储的数量
            else:
                choices = db_session.query(Choice).order_by(func.rand(Choice.choice_id))[0:choiceSize]
            if count_short_answer < shortAnswerSize:
                short_answers = db_session.query(ShortAnswer).all()
                message2 = '题库中简答题不够%s个, 现已全部引用' % shortAnswerSize
            else:
                short_answers = db_session.query(ShortAnswer).order_by(func.rand(ShortAnswer.short_answer_id))[0:shortAnswerSize]
            if count_program < programSize:
                programs = db_session.query(Program).all()
                message3 = '题库中简答题不够%s个, 现已全部引用' % programSize
            else:
                programs = db_session.query(Program).order_by(func.rand(Program.program_id))[0:programSize]
            # 创建试卷对象
            test_pager = TestPager(test_pager_name=name, test_pager_type=type, test_pager_choice_score=choiceScore,
                                   test_pager_short_answer_score=shortAnswerScore, test_pager_program_score=programScore,
                                   test_pager_choice_num=choiceSize, test_pager_short_answer_num=shortAnswerSize,
                                   test_pager_program_num=programSize, test_pager_total_score=totalscore)
            # 选择题，简答题，程序设计题绑定到试卷中

templates/front/front_add_program.html
{% extends "front/front_teacher_info.html" %}

{% block mainContent %}
    <div id="right" style="float: right;">
    <div id="menu-right" class="">
        <form method="post" action="">
            <div id="right-top" class="">
                <h1>程序设计题 题库管理</h1>
                <h2>添加程序设计题</h2>
            </div>
            <div id="right-bottom">
                <p id="" class="p2">
                    题目：
                                <textarea name="content" cols="88" rows="10"></textarea>
                </p>
                <p class="p2">
                    答案：
                                <textarea name="result" cols="88" rows="10"></textarea>
                </p>
                <p class="p2">
                    语言：
                    <select name="type">
                        <option value="python" name="python">python</option>
                        <option value="java" name="java">java</option>
                    </select>
                </p>
                <div class="p1">
                    <button type="submit" class="btn btn-info">保存</button>
                    <button type="reset" class="btn btn-danger">重置</button>
                </div>
              </div>
        </form>
    </div>
        {% if message != None %}

        {% if message == 'success' %}
            <script>
                xtalert.alertSuccess('添加成功！')
            </script>
        {% else %}
            <script>
                xtalert.alertInfoToast("{{ message }}")
            </script>
        {% endif %}

    {% endif %}
    </div>
{% endblock %}

templates/front/front_add_test_page.html
{% extends "front/front_teacher_info.html" %}

{% block mainContent %}
    {% if message %}
        <script>
            xtalert.alertError("{{ message }}");
        </script>
    {% endif %}
<div id="main" class="" style="float: right; width: 990px; padding-left: 30px">
    <div id="right" class="">
		<form action="" method="post">
		<div id="right-top" class="">
			<h1>试卷管理</h1>
		</div>
		<div id="right-bottom" class="">
			<table id="r-b-center">
				<tr class="hang">
					<th colspan="3" style="text-align: center">(最新一期)考卷设置</th>
				</tr>
				<tr class="hang">
                	<th style="text-align:center;">题型</th>
                    <th style="text-align:center;">本张试卷中包含该类题的个数</th>
                    <th style="text-align:center;">每道题的分值</th>
                </tr>
				<tr  class="hang">
                	<td>选择题</td>
                    <td>
                        <select name="choiceSize">
                            {% for foo in range(1,50) %}
                                <option value="{{ loop.index }}">{{ loop.index }}</option>
                            {% endfor %}
                        </select>
                    </td>
                    <td>
                        <select name="choiceScore">
                            {% for foo in range(1,10) %}
                                <option value="{{ loop.index }}">{{ loop.index }}</option>
                            {% endfor %}
                        </select>
                    </td>
                </tr>
                <tr  class="hang">
                	<td>简答题</td>
                    <td>
                        <select name="shortAnswerSize">
                            {% for foo in range(1,10) %}
                                <option value="{{ loop.index }}">{{ loop.index }}</option>
                            {% endfor %}
                        </select>
                    </td>
                    <td>
                        <select name="shortAnswerScore">
                            {% for foo in range(1,20) %}
                                <option value="{{ loop.index }}">{{ loop.index }}</option>
                            {% endfor %}
                        </select>
                    </td>
                </tr>
                <tr  class="hang">
                	<td>程序题</td>
                     <td>
                        <select name="programSize">
                            {% for foo in range(1,10) %}
                                <option value="{{ loop.index }}">{{ loop.index }}</option>
                            {% endfor %}
                        </select>
                    </td>
                    <td>
                        <select name="programScore">
                            {% for foo in range(1,50) %}
                                <option value="{{ loop.index }}">{{ loop.index }}</option>
                            {% endfor %}
                        </select>
                    </td>
                </tr>
                <tr  class="hang">
                	<td>生成试卷的类型</td>
                    <td>
                        <select name="type" style="width: 80px">
                            <option value="python" name="python">python</option>
                            <option value="java" name="java">java</option>
                        </select>
                    </p>
                    </td>
                    <td></td>
                </tr>
                <tr class="hang">
                    <td>试卷名称</td>
                    <td>
                        <input type="text" name="name" placeholder="本张试卷的名称">
                    </td>
                    <td></td>
                </tr>
                <tr  class="hang">
                	<td colspan="3">
                    	<center>
                    	<button type="submit" class="btn btn-success">生成试卷</button>
                        </center>
                    </td>
                </tr>
			</table>
		</div>
		</form>
	</div>
</div>
    <script>
        xtalert.alertSuccess('试卷添加成功，试卷总分: '+{{ totalScore }})
    </script>
{% endblock %}

templates/front/front_base.html
{% from 'common/_macro.html' import static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ static('front/css/mystyle.css') }}">
    <link rel="stylesheet" href="{{ static('common/css/bootstrap.min.css') }}">
    {% block title %}
{#        页面标题#}
    {% endblock %}
    {% block head %}
{#        页面添加css，js#}
    {% endblock %}
</head>
<body>
<div>
    <div id="main_top">
        <img src="{{ static('common/images/logo.png') }}" alt="这个一个logo" class="logo-div">
        <div id="main_top_list">
            <a href="{{ url_for("front.exam") }}">在线考试</a>
            <a href="{{ url_for("front.studentCenter") }}">个人信息</a>
            <a href="{{ url_for("front.login_out") }}">[注销]</a>
        </div>
    </div>
    {% block mainContent %}
{#        页面主题信息#}
    {% endblock %}

</div>
</body>
</html>

templates/front/front_exam.html
{% extends "front/front_base.html" %}

{% block title %}
    <title>在线考试</title>
{% endblock %}

{% block mainContent %}
    <div id="main_menu">
            <div id="top">
                <h2>考试列表</h2>
            </div>
            <div id="menu">
                <table width="100%" align="center" style="border-bottom: 1px solid #ccc" >
                    <tr>
                        <th>序号</th>
                        <th>考试名称</th>
                        <th>考试时间</th>
                        <th>状态</th>
                        <th>总分</th>
                        <th>得分</th>
                        <th>操作</th>
                    </tr>
                    {% for score in Scores %}
                        <tr>
                            <th style="padding-left: 20px">{{ score.score_id }}</th>
                            <th>{{ score.socre_test_pager.test_pager_name }}</th>
                            <th>{{ score.socre_test_pager.test_pager_test_time }}</th>
                            <th>{{ score.score_state }}</th>
                            <th>{{ score.socre_test_pager.test_pager_total_score }}</th>
                            <th>{{ score.score_student_socre }}</th>
                            {% if score.score_state == '未参加考试' %}
                                <th><a href="{{ url_for('front.student_exam_pager', test_pager_id=score.socre_test_pager.test_pager_id) }}">开始考试</a></th>
                            {% elif score.score_state == '等待阅卷' %}
                                <th style="color: red">等待阅卷</th>
                            {% elif score.score_state == '已经批阅' %}
                                <th><a href="{{ url_for("front.front_student_view_exam_pager", test_pager_id=score.socre_test_pager.test_pager_id) }}">查看试卷</a></th>
                            {% endif %}
                        </tr>
                    {% endfor %}

                </table>
            </div>
    </div>
{% endblock %}

templates/front/front_manager_choice.html
{% extends "front/front_teacher_info.html" %}

{% block addStyle %}
    <script src="{{ static("front/js/update_choice.js") }}"></script>
{% endblock %}

{% block mainContent %}
<div id="main" class="" style="float: right;width: 990px">
    <div id="right-top" class="">
        <h1 class="gl">选择题 题库管理</h1>
        <div class="tianjia">
            <a href="{{ url_for("front.add_choice") }}">添加新题</a>
        </div>
    </div>
    <div id="right-bottom" class="">
        <div id="r-b-center" class="">
            <table cellpadding="0" cellspacing="0" width="990px">
                <tr>
                    <th id="bianhao">编号</th>
                    <th id="timu" style="width: 80px;">所属语言</th>
                    <th id="tigan">题干</th>
                    <th id="daan" style="width: 50px;">答案</th>
                    <th id="bianji">编辑</th>
{#                    <th id="shancu">删除</th>#}
                </tr>
                {% for choice in choices %}
                    <tr data-id = {{ choice.choice_id }}
                        data-content="{{ choice.choice_content }}" data-choiceA="{{ choice.choice_option_A }}"
                        data-choiceB="{{ choice.choice_option_B }}" data-choiceC="{{ choice.choice_option_C }}"
                        data-choiceD="{{ choice.choice_option_D }}" data-choiceResult="{{ choice.choice_result }}"
                        data-result = "{{ choice.choice_result }}"
                    >
                        <td id="bianhao">{{ choice.choice_id }}</td>
                        <td id="type" style="width: 40px;">{{ choice.choice_type }}</td>
                        <td id="timu">{{ choice.choice_content[0:40] }}...</td>
                        <td id="daan" style="width: 30px;">{{ choice.choice_result }}</td>
                        <td id="bianji">
                            <button style="height: 35px;" class="btn btn-primary btn-lg updateBtn" data-toggle="modal" data-target="#myModal">
                                修改/查看
                            </button>
                        </td>
{#                        <td id="shancu"><input type="button" class="delBtn" value="删除" style="border:none"/></td>#}
                    </tr>
                {% endfor %}
            </table>
            {% block nextPage %}
                <center>
                    {% if page > 1 %}
                        {% with page=page - 1 %}
                            <td> <button type="button" class="btn btn-info"><a href="{{ url_for('front.manager_choice', page=page) }}">上一页</a></button>
                        {% endwith %}
                    {% endif %}
                    <span class="space-width"> </span>
                    {% if total >= ChOICE_PAGE_SIZE %}
                        {% with page=page + 1  %}
                            <td> <button type="button" class="btn btn-info"><a href="{{ url_for('front.manager_choice', page=page) }}">下一页</a></button>
                        {% endwith %}
                    {% endif %}
                </center>
            {% endblock %}
        </div>
    </div>
</div>

<!-- 模态框（Modal） -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
					&times;
				</button>
				<h4 class="modal-title" id="myModalLabel">
					编辑题目
				</h4>
			</div>
			<div class="modal-body" style="margin: 0 auto; font-size: 20px; width: 550px;">
                <form class="form-horizontal" method="post">
                    <div style="visibility:hidden"><input name="choiceId" type="text" value=""></div>
                  <div class="form-group">
                    <label name="name" for="inputName" class="col-sm-2 control-label">题目</label>
                    <div class="col-sm-10">
                      <input name="content" type="text" class="form-control" id="inputContent" placeholder="题目">
                    </div>
                  </div>
                  <div class="form-group">
                    <label name="choiceA" for="inputChoiceA" class="col-sm-2 control-label">选项A</label>
                    <div class="col-sm-10">
                      <input name="choiceA" type="text" class="form-control" id="inputChoiceA" placeholder="选项A">
                    </div>
                  </div>
                  <div class="form-group">
                    <label name="choiceB" for="inputChoiceB" class="col-sm-2 control-label">选项B</label>
                    <div class="col-sm-10">
                      <input name="choiceB" type="text" class="form-control" id="inputChoiceB" placeholder="选项B">
                    </div>
                  </div>
                    <div class="form-group">
                        <label name="choiceC" for="inputChoiceC" class="col-sm-2 control-label">选项C</label>
                        <div class="col-sm-10">
                          <input name="choiceC" type="text" class="form-control" id="inputChoiceC" placeholder="选项C">
                        </div>
                  </div>
                    <div class="form-group">
                    <label name="choiceD" for="inputChoiceD" class="col-sm-2 control-label">选项D</label>
                    <div class="col-sm-10">
                      <input name="choiceD" type="text" class="form-control" id="inputChoiceD" placeholder="选项D">
                    </div>
                  </div>
                    <div class="form-group">
                        <label class="col-sm-3">正确答案</label>
                        <div class="col-sm-9">
                            <select name="choiceResult" id="choice_result">
                                <option value="A">A</option>
                                <option value="B">B</option>
                                <option value="C">C</option>
                                <option value="D">D</option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button id="save-info-btn" type="button" class="btn btn-primary saveBtn">保存</button>
            </div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal -->
</div>
{% endblock %}

templates/front/front_manager_score.html
{% extends "front/front_teacher_info.html" %}

{% block addStyle %}
    <script src="{{ static("front/js/update_score.js") }}"></script>
{% endblock %}

{% block mainContent %}
<div id="main" class="" style="float: right;width: 990px">
    <div id="right-top" class="">
        <h1 class="gl">成绩管理</h1>
    </div>
    <div id="right-bottom" class="">
        <div id="r-b-center" class="">
            <table cellpadding="0" cellspacing="0" width="990px">
                <tr>
                    <th id="bianhao">班级</th>
                    <th id="timu" style="width: 120px;">学生</th>
                    <td id="tigan">考试名称</td>
                    <th id="daan" style="width: 150px;">试卷状态</th>
                    <th id="bianji">考生得分</th>
                </tr>
                {% for score in scores %}
                    <tr>
                        <td id="bianhao">{{ score.socre_student.student_class.class_name }}</td>
                        <td id="type" style="width: 40px;">{{ score.socre_student.student_name }}</td>
                        <td id="timu">{{ score.socre_test_pager.test_pager_name }}</td>
                        <td id="daan" style="width: 30px;">{{ score.score_state }}</td>
                        <td id="bianji">{{ score.score_student_socre }}</td>
                    </tr>
                {% endfor %}
            </table>
            {% block nextPage %}
                <center>
                    {% if page > 1 %}
                        {% with page=page - 1 %}
                            <td> <button type="button" class="btn btn-info"><a href="{{ url_for('front.manager_score', page=page) }}">上一页</a></button>
                        {% endwith %}
                    {% endif %}
                    <span class="space-width"> </span>
                    {% if total >= SCORE_PAGER_SIZE %}
                        {% with page=page + 1  %}
                            <td> <button type="button" class="btn btn-info"><a href="{{ url_for('front.manager_score', page=page) }}">下一页</a></button>
                        {% endwith %}
                    {% endif %}
                </center>
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

templates/front/front_teacher_info.html
{% extends "front/front_teacher_base.html" %}

{% block welcome %}
    {{ g.teacher_user.teacher_name }}老师，欢迎您
    <a href="{{ url_for("front.teacher_logout") }}">[注销]</a>
{% endblock %}

{% block mainContent %}
    {% set user = g.teacher_user %}
        <div style="float:right; margin-right: 80px;margin-top:20px;">
            <table class="table table-bordered" style="font-size: 18px; width: 850px;">
                <tbody>
                    <tr>
                        <td>姓名：</td>
                        <td>{{ user.teacher_name }}</td>
                    </tr>
                    <tr>
                        <td>邮箱：</td>
                        <td>{{ user.teacher_email }}</td>
                    </tr>
                    <tr>
                        <td>手机号：</td>
                        <td>{{ user.teacher_phone }}</td>
                    </tr>
                    <tr>
                    <tr>
                        <td>管理班级</td>
                        <td>{{ user.teacher_class }}</td>
                    </tr>
                    </tr>
                    <tr>
                        <td>加入时间：</td>
                        <td>{{ user.teacher_create_time }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
{% endblock %}

{% block nextPage %}

{% endblock %}